### ISSUE TITLE
Error while installing pillow

### ISSUE THREAD

**Issue by Sabin-of** [codesensei-courses/django-models#1]
Please solve the requirement.txt file as it contains an error while downloading the pillow. Difficult to start the new project as the site is broken while starting the project.

**Comment by rjekker** [comment]
Took a while to find time to look into this, sorry.

Apparently the exact Pillow version that will work on your system depends on several things, see: https://pillow.readthedocs.io/en/stable/installation.html

I will remove the version for pillow from the requirements file to fix this.

**Comment by codesensei-courses** [comment]
Fixed
